[project]
name = "agentzeroo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "openai-agents>=0.2.10",
    "python-dotenv>=1.1.1",
    "supabase>=2.17.0",
]
